name: Java CI with Maven Bhardwaj_code
on: 
 push :
  branches:
     - main
jobs:
  compile:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@4
      - name: Set up JSK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name : install  Maven
        run:
         sudo apt update
         sudo apt install maven -y
      - name: Built with Maven
        run: mvn compile
  security-check:
    runs-on: self-hosted
    needs: compile
    steps: 
     - uses: action/checkout@4
     - name: Trivy install
       run: >
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y 
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | 
          sudo apt-key add - 
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list 
          sudo apt-get update -y 
          sudo apt-get install trivy -y 
     - name: Trivy FS Scan
       run: trivy fs --format table -o fs-report.json .
     - name: Gitleaks install
       run: sudo apt install gitleaks -y
     - name: Gitleaks Code Scan
       run: gitleaks detect source . -r gitleaks-report.json -f json 
   
  test:
     runs-on: selt-hosted
     needs: security-check
     steps:
       - uses: actions/checkout@v4
       - name: Set up JDK 17 
         uses: actions/setup-java@v4
         with:
           java-version: "17"
           distribution: temurin
           cache: maven
       - name: Unit Test Case
         run: mvn test

         
